[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$SourceRoot,

    [string]$OutputRoot = (Join-Path $PSScriptRoot "..\artifact_anonymous"),

    [string]$SupplementPath = (Join-Path $PSScriptRoot "..\drafts\overleaf_submission\supp.tex")
)

$ErrorActionPreference = "Stop"

$source = (Resolve-Path -LiteralPath $SourceRoot).Path
$supplement = (Resolve-Path -LiteralPath $SupplementPath).Path
$repo = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$output = [System.IO.Path]::GetFullPath($OutputRoot)
$pathComparison = [System.StringComparison]::OrdinalIgnoreCase

function Test-IsChildPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Candidate,

        [Parameter(Mandatory = $true)]
        [string]$Parent
    )

    $normalizedParent = $Parent.TrimEnd(
        [System.IO.Path]::DirectorySeparatorChar,
        [System.IO.Path]::AltDirectorySeparatorChar
    ) + [System.IO.Path]::DirectorySeparatorChar
    return $Candidate.StartsWith($normalizedParent, $pathComparison)
}

if ($output.Equals($source, $pathComparison) -or (Test-IsChildPath $output $source)) {
    throw "OutputRoot must not be inside SourceRoot."
}
if (-not (Test-IsChildPath $output $repo)) {
    throw "OutputRoot must be a child directory of the repository: $repo"
}

$suppText = Get-Content -LiteralPath $supplement -Raw
$s9Start = $suppText.IndexOf("\section*{S9.")
$s10Start = $suppText.IndexOf("\section*{S10.")
if ($s9Start -lt 0 -or $s10Start -le $s9Start) {
    throw "Could not locate S9/S10 boundaries in $supplement."
}

$s9Text = $suppText.Substring($s9Start, $s10Start - $s9Start)
$expectedJson = [regex]::Matches($s9Text, '\\path\{([^{}]+\.json)\}') |
    ForEach-Object { $_.Groups[1].Value } |
    Sort-Object -Unique

if ($expectedJson.Count -eq 0) {
    throw "No S9 JSON filenames were parsed from $supplement."
}

$sourceFiles = Get-ChildItem -LiteralPath $source -File -Recurse
$byName = @{}
foreach ($file in $sourceFiles) {
    if (-not $byName.ContainsKey($file.Name)) {
        $byName[$file.Name] = [System.Collections.Generic.List[object]]::new()
    }
    $byName[$file.Name].Add($file)
}

$missing = [System.Collections.Generic.List[string]]::new()
$duplicates = [System.Collections.Generic.List[string]]::new()
$resolved = [System.Collections.Generic.List[object]]::new()

foreach ($name in $expectedJson) {
    if (-not $byName.ContainsKey($name)) {
        $missing.Add($name)
        continue
    }

    $matches = $byName[$name]
    if ($matches.Count -ne 1) {
        $duplicates.Add("$name`t$($matches.FullName -join ';')")
        continue
    }
    $resolved.Add($matches[0])
}

$reportDir = Join-Path $repo "experiments"
$reportPath = Join-Path $reportDir "artifact_recovery_report.txt"
$report = @(
    "Generated: $([DateTime]::Now.ToString('s'))"
    "Source: $source"
    "Expected S9 JSON: $($expectedJson.Count)"
    "Resolved: $($resolved.Count)"
    "Missing: $($missing.Count)"
    "Duplicate basenames: $($duplicates.Count)"
    ""
    "[missing]"
    ($missing -join "`n")
    ""
    "[duplicates]"
    ($duplicates -join "`n")
)
Set-Content -LiteralPath $reportPath -Value $report -Encoding utf8

if ($missing.Count -gt 0 -or $duplicates.Count -gt 0) {
    throw "Artifact recovery is incomplete. See $reportPath."
}

if (Test-Path -LiteralPath $output) {
    $resolvedOutput = (Resolve-Path -LiteralPath $output).Path
    $marker = Join-Path $resolvedOutput ".anonymous-artifact-staging-root"
    if (-not (Test-IsChildPath $resolvedOutput $repo)) {
        throw "Refusing to replace an output directory outside the repository: $resolvedOutput"
    }
    if (-not (Test-Path -LiteralPath $marker -PathType Leaf)) {
        throw "Refusing to replace an unmarked directory: $resolvedOutput"
    }
    Remove-Item -LiteralPath $resolvedOutput -Recurse -Force
}

$resultsDir = Join-Path $output "results"
$codeDir = Join-Path $output "code"
$configDir = Join-Path $output "configs"
$manifestDir = Join-Path $output "manifests"
New-Item -ItemType Directory -Force -Path $resultsDir, $codeDir, $configDir, $manifestDir | Out-Null
Set-Content -LiteralPath (Join-Path $output ".anonymous-artifact-staging-root") `
    -Value "Generated by build_anonymous_artifact.ps1" -Encoding ascii

foreach ($file in $resolved) {
    Copy-Item -LiteralPath $file.FullName -Destination (Join-Path $resultsDir $file.Name)
}

$codeItems = @(
    "src\v3_premerger",
    "src\fastv_bench.py",
    "scripts\official_scorers.py",
    "scripts\rescore_official.py"
)
foreach ($item in $codeItems) {
    $path = Join-Path $repo $item
    if (Test-Path -LiteralPath $path) {
        Copy-Item -LiteralPath $path -Destination $codeDir -Recurse
    }
}

if (Test-Path -LiteralPath (Join-Path $repo "configs")) {
    Get-ChildItem -LiteralPath (Join-Path $repo "configs") | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination $configDir -Recurse
    }
}

$identityPatterns = @(
    '/media/disk2/',
    '/home/',
    '/data/models/',
    'YZX',
    'Jiangnianheng',
    'Chenkaida',
    'Code-Yan-ZX'
)
$textExtensions = @(".json", ".jsonl", ".yaml", ".yml", ".toml", ".txt", ".md", ".py", ".sh", ".ps1")
$findings = [System.Collections.Generic.List[string]]::new()
foreach ($file in Get-ChildItem -LiteralPath $output -File -Recurse) {
    if ($textExtensions -notcontains $file.Extension.ToLowerInvariant()) {
        continue
    }
    $text = Get-Content -LiteralPath $file.FullName -Raw -ErrorAction SilentlyContinue
    foreach ($pattern in $identityPatterns) {
        if ($text -match [regex]::Escape($pattern)) {
            $relative = [System.IO.Path]::GetRelativePath($output, $file.FullName)
            $findings.Add("$relative`t$pattern")
        }
    }
}

$findingsPath = Join-Path $manifestDir "anonymity_findings.tsv"
Set-Content -LiteralPath $findingsPath -Value @("file`tpattern") -Encoding utf8
if ($findings.Count -gt 0) {
    Add-Content -LiteralPath $findingsPath -Value $findings -Encoding utf8
    throw "Anonymity scan found local paths or identity strings. See $findingsPath."
}

$hashRows = foreach ($file in Get-ChildItem -LiteralPath $output -File -Recurse | Sort-Object FullName) {
    $relative = [System.IO.Path]::GetRelativePath($output, $file.FullName).Replace("\", "/")
    $hash = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    "$hash  $relative"
}
Set-Content -LiteralPath (Join-Path $manifestDir "SHA256SUMS") -Value $hashRows -Encoding ascii

Write-Host "Anonymous artifact staged at $output"
Write-Host "S9 JSON files: $($resolved.Count)/$($expectedJson.Count)"
Write-Host "SHA-256 manifest: $(Join-Path $manifestDir 'SHA256SUMS')"
